spring:
  datasource: # druid 数据源
    type: com.alibaba.druid.pool.DruidDataSource
    # MySQL 版本: 8.0.25
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/tracing_sys?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai&autoReconnect=true
    username: root
    password: 123456


  #    password:
  jdbc:
    template: # 设置超时，单位：s
      query-timeout: 5
