server:
  port: 8888

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/guess?useSSL=false&serverTimezone=UTC
    username: root
    password: "123456"
  main:
    banner-mode: off